/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.azhar.hospital.view;

import com.azhar.hospital.db.vo.UsersVo;

/**
 *
 * @author fastox
 */
public class Home extends javax.swing.JFrame {

    public static UsersVo usersVo;

    /**
     * Creates new form Home
     */
    public Home(UsersVo usersVo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usersVo = usersVo;
        getUserLevel();
    }

    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        getUserLevel();
    }

    protected void getUserLevel() {
        switch (usersVo.getUsersType().getType()) {
            case "admin":
                mDoctor.setEnabled(false);
                mReceptionist.setEnabled(false);
                mNurse.setEnabled(false);
                break;
            case "doctor":
                mAdmin.setEnabled(false);
                mReceptionist.setEnabled(false);
                mNurse.setEnabled(false);
                break;
            case "nurse":
                mAdmin.setEnabled(false);
                mReceptionist.setEnabled(false);
                mDoctor.setEnabled(false);
                break;
            case "reception":
                mAdmin.setEnabled(false);
                mNurse.setEnabled(false);
                mDoctor.setEnabled(false);
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mAdmin = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mDoctor = new javax.swing.JMenu();
        mNurse = new javax.swing.JMenu();
        mReceptionist = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\Programming\\Java\\Projects\\Hospital_System\\images\\background.jpg")); // NOI18N

        mAdmin.setText("Admin");

        jMenuItem1.setText("Add new user");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mAdmin.add(jMenuItem1);

        jMenuBar1.add(mAdmin);

        mDoctor.setText("Doctor");
        jMenuBar1.add(mDoctor);

        mNurse.setText("Nurse");
        jMenuBar1.add(mNurse);

        mReceptionist.setText("Receptionist");

        jMenuItem2.setText("Patient Info");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mReceptionist.add(jMenuItem2);

        jMenuBar1.add(mReceptionist);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        UsersView usersView = new UsersView();
        usersView.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        PatientInfoView patientInfoView = new PatientInfoView();
        patientInfoView.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mAdmin;
    private javax.swing.JMenu mDoctor;
    private javax.swing.JMenu mNurse;
    private javax.swing.JMenu mReceptionist;
    // End of variables declaration//GEN-END:variables
}
